### ISSUE TITLE
readme 中出现的 openresty -p 是什么命令？

### ISSUE THREAD

**Issue by daodao97** [362228416/openresty-web-dev#1]

**Comment by 362228416** [comment]
@daodao97 
作用跟nginx一样，以下两句命令是等价的，你可以认为openresty，是nginx的一个快捷方式，-p 用来指定nginx的根目录，可以用一个nginx，运行多个进程指向不同的根目录
/usr/local/openresty/bin/openresty -p dir
/usr/local/openresty/nginx/sbin/nginx -p dir
因为我还单独装了nginx，为了把他们区分开，我把openresty加到环境变量，所以都是使用openresty来启动的

**Comment by daodao97** [comment]
看到你在文章中提到有异常捕获，错误所见即所得的封装，没看到源码在哪里，能否分享一下

**Comment by 362228416** [comment]
@daodao97 
这部分准备会单独介绍，这两天就会写出来。敬请留意

**Comment by 362228416** [comment]
代码封装代码已更新 🤔

发自我的 iPhone
